### ISSUE TITLE
Extension does not load Fixtures as a service in v6

### ISSUE THREAD

**Issue by Cethy** [BehatExtension/DoctrineDataFixturesExtension#27]
| Q                    | A
| -------------------- | -----
| Bug report?          | yes
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Project version      | 6.0

As stated in https://github.com/BehatExtension/DoctrineDataFixturesExtension/issues/22, the extension should load fixtures w/ non-optional arguments. But it does not.

Because the `BehatExtension\DoctrineDataFixturesExtension\Service\Loader` extends the `Doctrine\Common\DataFixtures\Loader` which is not responsible for loading fixtures from DI (`Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader` is).

**Comment by Spomky** [comment]
Hi,

I explained the reasons why DI is not possible possible from this Behat extension in https://github.com/BehatExtension/DoctrineDataFixturesExtension/issues/22#issuecomment-427668030 and https://github.com/BehatExtension/DoctrineDataFixturesExtension/issues/22#issuecomment-432122894.

The only way to use fixtures with non-optional arguments is to declare these fixtures as services and tagged with `doctrine.fixture.orm`.

**Comment by Spomky** [comment]
In this particular case, the extension is not responsible of the fixture loading, your bundle is.
Please have a look at [this fixture](https://github.com/BehatExtension/DoctrineDataFixturesExtension/blob/v6.0/tests/DemoBundle/DataFixtures/ORM/AnotherProductLoader.php) or [this one](https://github.com/BehatExtension/DoctrineDataFixturesExtension/blob/v6.0/tests/DemoBundle/Tests/IsolatedProductLoader.php) and [their definitions](https://github.com/BehatExtension/DoctrineDataFixturesExtension/blob/v6.0/tests/DemoBundle/Resources/config/services.php#L30-L34).
They are correctly loaded and used by the extension.

**Comment by Cethy** [comment]
The tests does not cover the `DependentFixtureInterface` usage. Please, have a look at [this branch](https://github.com/Cethy/DoctrineDataFixturesExtension/tree/break_v6_tests).
I updated my PR to cover this bug.

**Comment by Spomky** [comment]
OK I misunderstood your concerns.
You are right I missed the DependentFixtureInterface and OrderedFixtureInterface capabilities.
I will check your PR.

Let move the discussion to #28.
